#!/bin/bash
gh act -j $1 -P ubuntu-latest=-self-hosted | tee log/last.log

# save output to log
#gh act -j $1 -P ubuntu-latest=-self-hosted | tee log/last.log

# provide token
#gh act -j $1 -s GITHUB_TOKEN="$(gh auth token)" -P ubuntu-latest=-self-hosted

# use different container
#gh act -j hello-world -P ubuntu-latest=catthehacker/ubuntu:pwsh-latest
